const Data = [
    
    {
        id: 1,
        num: 0,
        title:"108 Panchantantra Stories ",
        author:"by Maple Press | 1 September 2020",
        price: 98,
        img: "https://m.media-amazon.com/images/I/71rmxx8P2qL._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 2,
        num: 0,
        title:"My First Book of Pencil Control",
        author:"by Wonder House Books  | 25 April 2018",
        price: 57,
        img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 3,
        num: 0,
        title:"Brain the Silly Panda",
        author:"by Maple Press | 1 September 2021",
        price: 86,
        img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 4,
        num: 0,
        title:"Blossom Moral Story Book for Kids",
        author:"by Content Team at Target Publication",
        price: 80,
        img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 5,
        num: 0,
        title:"Early Learning Library Pack 1",
        author:"by Wonder House Books | 6 Decemeber 2020",
        price: 289,
        img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 6,
        num: 0,
        title:"Pre-School Activities Pack",
        author:"by Om Books Editorial Team | 1 January 2021",
        price: 693,
        img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 7,
        num: 0,
        title:"101 Panchatantra Stories for Children",
        author:"by Om Books Editorial Team | 30 September 2020",
        price: 135,
        img: "https://m.media-amazon.com/images/I/9173YBkMIsL._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 8,
        num: 0,
        title:"My First Book of Pencil Control",
        author:"by Wonder House Books | 25 April 2018",
        price: 89,
        img: "https://m.media-amazon.com/images/I/810OOg88LoL._AC_UY327_FMwebp_QL65_.jpg",
    },
    {
        id: 9,
        num: 0,
        title:"Willy the silly Panda",
        author:"by Rebecca Smith | 14 December 2021",
        price: 120,
        img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
    },
    // {
    //     id: 10,
    //     num: 0,
    //     title:"Encyclopedia: Amazing Questions and Answers Science",
    //     author:"by Om Books Editorial Team | 25 November 2018",
    //     price: 143,
    //     img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
    // },
    // {
    //     id: 11,
    //     num: 0,
    //     title:"My First Book of Pencil Control",
    //     author:"by Wonder House Books  | 25 April 2018",
    //     price: 57,
    //     img: "https://m.media-amazon.com/images/I/81Gbz0XnW7L._AC_UY327_FMwebp_QL65_.jpg",
    // },
    // {
    //     id: 12,
    //     num: 0,
    //     title:"My First 1000 Words",
    //     author:"by Wonder House Books  | 1 January 2018",
    //     price: 149,
    //     img: "https://m.media-amazon.com/images/I/710-FI7QApL._AC_UY327_FMwebp_QL65_.jpg",
    // }
    
]
export default Data